### ISSUE TITLE
add site-level Discord server switcher

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#86]
## Description

In the event the bot is added to multiple Discord servers, a global server switcher would serve well when considering fetching the stored server configuration (holds server ID and list of roles to be treated as "admin" for access control on the frontend)

Concept:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/5033303/170727411-f463503f-0e76-4a40-af45-2cf9fddf20eb.png">

## Todo

- [ ] add global Discord server switcher
- [ ] fetch server configuration in hooks, add to `event.locals` (?)
- [ ] remove server switcher from `/admin/configure`, lean on global app switcher to load and change config
- [ ] **requirement**: switcher should only show servers that both the bot and authenticated user are members of
