### ISSUE TITLE
add access control to frontend, customize user session

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#88]
## Description

Functionality has been built to support displaying Administration pages, links, and making API calls. However, with the addition of [next-auth](https://next-auth.js.org/) we do not yet have `session.user.isAdmin` set on the user session. Add `isAdmin` to user session

## Todo

- [ ] add `isAdmin` to user session
- [ ] fetch server configuration and determine is authenticated user has the appropriate roles to be an "admin"
	- [ ] add Discord API call from Bot to fetch Discord member roles
