### ISSUE TITLE
`/docs` - search docs with a query

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#90]
## Description

Add `/docs` command to search for docs results, or `/docs-search` or `/search-docs`?

## Usage

```
/docs "data modeling"
```

should return results such as:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/5033303/170732099-c2014c9f-fb0d-4734-9161-3a3c00f8da61.png">

## Todo

- [ ] add `/docs` command
- [ ] call [docs' search API](https://github.com/aws-amplify/docs/blob/0d862fde9e8843afde43b1b14a6ac9b6189be6cd/src/components/SearchBar/index.tsx#L11-L14)
- [ ] return results as embed
- [ ] **requirement**: enabled by default
- [ ] **requirement**: add single "query" argument
- [ ] **optional**: reply privately with results and allow caller to interactively sift through results?
- [ ] **optional**: allow user to select result and retrieve direct URL
