### ISSUE TITLE
threads: promote similar GitHub issues to new questions

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#91]
## Description

Add support to promote similar GitHub issues in new questions (threads). By doing so, it allows questioner to find relevant results to their question. Sometimes questions have already been filed as bugs, features, or general question issues in GitHub. This can also provide value where questions are not immediately responded to, enabling questioners to potentially find others experiencing similar issues.

## Todo

- [ ] retrieve relevant GitHub results, ranked by channel association (i.e. questions asked in `cli-help` should weigh issues in `amplify-cli` repo higher)
- [ ] make call to retrieve results after thread has been created and saved in db
- [ ] return results as embed to thread
- [ ] **optional**: reply privately with results?
- [ ] **optional**: allow user to mark issue as "related" or "relevant" (requires change to thread db model)
