### ISSUE TITLE
add office hours schedule with Discord event links to frontend application

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#92]
## Description

Add a public-facing `/schedule` page to display office hours schedule, guests, topics, and links to scheduled Discord events. Inspiration: https://www.reactiflux.com/schedule

## Todo

- [ ] add `/schedule` page to SvelteKit site
- [ ] create OfficeHours database model to hold items
- [ ] add admin form to create schedule items (e.g. `/admin/office-hours`)
	- [ ] form should create event in Discord
	- [ ] form should save office hours item in database (with event link from above)
- [ ] add admin form to update upcoming schedule items
	- [ ] form should update event in Discord
	- [ ] form should update record in database
