### ISSUE TITLE
add metrics page for questions (threads)

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#93]
## Description

Question (thread) data is captured at a high-level, and while a simple endpoint exists to retrieve these results it would be nice if there was a page to graphically display this data.

Reference: https://www.npmjs.com/package/@carbon/charts-svelte

## Todo

- [ ] decide on valuable metrics to display (e.g. time-to-resolve, whether there was staff involvement, etc.)
- [ ] add page to display metrics (e.g. `/admin/metrics`)
- [ ] add charts package to display metrics
- [ ] **requirement**: page should be restricted to admins
- [ ] **optional**: add fine-grained access control for roles that are able to access metrics (instead of global `isAdmin`), allowing non-admin members to view metrics
