### ISSUE TITLE
`/github` feature: search GitHub issues from a repository

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#94]
## Description

Add support for searching issues from a GitHub repository. Unfortunately adding this support may exceed the supported command depth by Discord, which would motivate the need for a separate `/issues` or `/search` command

## Todo 

- [ ] add command support for searching GitHub issues
- [ ] decide whether it is justified to create a new command
	- [ ] deprecate this issue in favor of tracking new issue if so, copy intent
- [ ] **requirement**: results should be displayed in an embed
- [ ] **requirement**: only show subset of results (e.g. first 5)
- [ ] **optional**: add buttons to allow callers to select an issue and retrieve the URL
- [ ] **optional**: privately respond with issue list
- [ ] **optional**: paginating results with buttons
